#��Ŀ��� ��Ҫ����WebSocketConfig.java ;  pom.xml  ; competition.js  ; HznuctfApplication
#���ݿ�����
#����
jdbc.driver = com.mysql.cj.jdbc.Driver
jdbc.url = jdbc:mysql://localhost:3306/hznuctf?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
jdbc.username=root
jdbc.password=123456

#������·������
server.servlet.context-path=/hznuctf
#Mybatis
mybatis_config_file = mybatis-config.xml
mapper_path=/mapper/**.xml
entity_package=com.ctfplatform.hznuctf.entity

#�Ȳ�������
debug: true
spring:
devtools:
restart:
enabled: true  #���ÿ����Ȳ���
freemarker:
cache: false    #ҳ�治���ػ��棬�޸ļ�ʱ��Ч

#�ʼ�����
spring.mail.host=smtp.126.com
spring.mail.username=security514@126.com
#����POP3֮�����õĿͻ�����Ȩ��
spring.mail.password=301security
spring.mail.default-encoding=UTF-8

#slf4j��־ϵͳ
logging.path=/hznuctfLog
logging.level.org.springframework.boot.autoconfigure: ERROR 